version: "3.1"

services:
  db:
    image: mysql
    restart: always
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: demo_pasha
    ports:
      - "3306:3306"
  app:
    image: my-java-app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_db:
